// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhm7mdmJmTEImHxEWmM0zHYbA6lTuY87k',
    appId: '1:696462825579:web:53bfbd0de7cb159a17792e',
    messagingSenderId: '696462825579',
    projectId: 'seen-e1615',
    authDomain: 'seen-e1615.firebaseapp.com',
    storageBucket: 'seen-e1615.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGkIAtfP50DZ2RrZVGSyGSATF70eyuu6k',
    appId: '1:696462825579:android:f3caa1de84bb9b7b17792e',
    messagingSenderId: '696462825579',
    projectId: 'seen-e1615',
    storageBucket: 'seen-e1615.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWYP2jN5eRTV6EEbVX5Hr4CnE1Ly5HLXA',
    appId: '1:696462825579:ios:8f7278ced8bca34317792e',
    messagingSenderId: '696462825579',
    projectId: 'seen-e1615',
    storageBucket: 'seen-e1615.firebasestorage.app',
    iosBundleId: 'com.example.seen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWYP2jN5eRTV6EEbVX5Hr4CnE1Ly5HLXA',
    appId: '1:696462825579:ios:8f7278ced8bca34317792e',
    messagingSenderId: '696462825579',
    projectId: 'seen-e1615',
    storageBucket: 'seen-e1615.firebasestorage.app',
    iosBundleId: 'com.example.seen',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBhm7mdmJmTEImHxEWmM0zHYbA6lTuY87k',
    appId: '1:696462825579:web:4db0ddd223a0193e17792e',
    messagingSenderId: '696462825579',
    projectId: 'seen-e1615',
    authDomain: 'seen-e1615.firebaseapp.com',
    storageBucket: 'seen-e1615.firebasestorage.app',
  );
}
